    global:
      resolve_timeout: 1m
      slack_api_url: 'hxtxtxpsx://hooks.slack.com/services/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'
    receivers:
    - name: 'slack-notificaions'
      slack_configs:
      - channel: '#your-slack-channel'
        send_resolved: true
        api_url: 'https://slack-webhook-url'
    route:
      group_by: ['alertname', 'severity']
      group_interval: 5m
      group_wait: 10s
      receiver: 'slack-notificaions'
      repeat_interval: 3h

